import uuid
from datetime import datetime
from enum import Enum

from sqlalchemy import Column
from sqlmodel import Field

from app.core.db_types import PortableJSONB
from app.models.base import TimestampedModel


class TaskType(str, Enum):
    # Depth-0 phase tasks — one per existing batch engine call, unchanged
    # execution, just now also represented as a research_task row for
    # tree/traceability purposes (Group D2 design decision #1).
    seed_crawl = "seed_crawl"
    ai_classification = "ai_classification"
    seed_intents = "seed_intents"
    serp_batch = "serp_batch"
    prompt_family_batch = "prompt_family_batch"
    ai_visibility_batch = "ai_visibility_batch"
    competitor_discovery_batch = "competitor_discovery_batch"
    # Depth >= 1 follow-up tasks — proposed by the Research Planner,
    # accepted/executed by the Orchestrator.
    competitor_deep_dive = "competitor_deep_dive"
    page_compare = "page_compare"
    query_expansion = "query_expansion"
    validate_finding = "validate_finding"
    # Part F.5-10 — surface-aware follow-ups. One extra targeted Google
    # check, or one extra targeted probe on a specific AI surface, for a
    # single intent the Planner has a concrete reason to double-check
    # (e.g. "a competitor dominates Google here — do they also dominate
    # ChatGPT?"). Distinct from the fixed serp_batch/ai_visibility_batch
    # phases, which cover the whole intent set once per run.
    search_google = "search_google"
    ai_visibility_chatgpt = "ai_visibility_chatgpt"
    ai_visibility_gemini = "ai_visibility_gemini"
    ai_visibility_claude = "ai_visibility_claude"
    validate_cross_surface_finding = "validate_cross_surface_finding"


DISCOVERY_TASK_TYPES = frozenset(
    {
        TaskType.competitor_deep_dive,
        TaskType.page_compare,
        TaskType.query_expansion,
        TaskType.validate_finding,
        TaskType.search_google,
        TaskType.ai_visibility_chatgpt,
        TaskType.ai_visibility_gemini,
        TaskType.ai_visibility_claude,
        TaskType.validate_cross_surface_finding,
    }
)
"""Task types the Research Planner is allowed to propose. Phase task types
(seed_crawl, ai_classification, ...) run automatically once per pipeline —
never Planner-proposed. The Orchestrator enforces this allow-list when
accepting Planner suggestions (Group D2 design: Planner suggests,
Orchestrator decides)."""


class TaskStatus(str, Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    skipped_duplicate = "skipped_duplicate"


class ResearchTask(TimestampedModel, table=True):
    """One node in the research tree. parent_task_id traces what triggered
    this investigation (Group D2 design: 'this research started from
    what?') — depth-0 tasks (no parent) are the fixed pipeline phases;
    deeper tasks are Planner-proposed follow-ups the Orchestrator accepted.
    """

    __tablename__ = "research_tasks"

    research_run_id: uuid.UUID = Field(foreign_key="research_runs.id", index=True)
    parent_task_id: uuid.UUID | None = Field(default=None, foreign_key="research_tasks.id", index=True)
    store_id: uuid.UUID = Field(foreign_key="stores.id", index=True)

    task_type: TaskType
    reason: str | None = None
    hypothesis: str | None = None
    priority: float = Field(default=0.5)
    depth: int = Field(default=0)
    status: TaskStatus = Field(default=TaskStatus.pending)

    input: dict = Field(default_factory=dict, sa_column=Column(PortableJSONB))
    result_summary: str | None = None
    evidence_ids: list[str] = Field(default_factory=list, sa_column=Column(PortableJSONB))
    discovered_entities: dict = Field(default_factory=dict, sa_column=Column(PortableJSONB))
    created_tasks_count: int = Field(default=0)
    cost: float | None = None
    fingerprint: str = Field(index=True)

    # Part G-B4 — explicit dead-end tracking, set once the task finishes
    # (stay at their defaults / None for pending/running/failed/
    # skipped_duplicate tasks). new_findings_count/new_evidence_count are
    # exact counts from this task's own output; new_competitors_count only
    # applies to competitor_discovery_batch. affected_opportunities_count is
    # filled in later by findings_engine.backfill_task_opportunity_impact,
    # once Opportunities exist (they're generated by a later agent_run, long
    # after this task's own row is already completed) — 0 until then, same
    # 'not yet known != zero value' distinction as elsewhere, except here
    # it's genuinely 0 until backfilled rather than a fake placeholder.
    new_findings_count: int = Field(default=0)
    new_evidence_count: int = Field(default=0)
    new_competitors_count: int = Field(default=0)
    affected_opportunities_count: int = Field(default=0)
    useful: bool | None = Field(default=None, index=True)

    started_at: datetime | None = None
    completed_at: datetime | None = None
