"use client";
/* eslint-disable @next/next/no-img-element -- audited external page images */
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {Badge} from "@/components/ui/Badge";
import {Card} from "@/components/ui/Card";
import {EmptyState,ErrorState,LoadingState} from "@/components/ui/States";
import {IconArrowLeft,IconOverview} from "@/components/ui/icons";
import {getPages,PageWorkspaceItem} from "@/lib/api";

const PAGE_LABELS:Record<string,string>={home:"الرئيسية",category:"تصنيف",product:"منتج",content:"محتوى",other:"أخرى"};
export default function PagesCenter(){const storeId=useParams<{id:string}>().id;const [pages,setPages]=useState<PageWorkspaceItem[]|null>(null);const [error,setError]=useState<string|null>(null);const [type,setType]=useState("all");useEffect(()=>{getPages(storeId).then((r)=>setPages(r.pages)).catch((e)=>setError(String(e)));},[storeId]);const visible=useMemo(()=>pages?.filter((p)=>type==="all"||p.page_type===type)??[],[pages,type]);if(error)return <ErrorState message={error}/>;if(!pages)return <LoadingState label="نجمع صفحات المتجر..."/>;return <div className="flex flex-col gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold text-primary">مركز الصفحات</p><h1 className="mt-1 text-2xl font-bold text-text">كل صفحات المتجر</h1><p className="mt-2 text-sm text-text-secondary">الرئيسية والتصنيفات والمنتجات والمحتوى في مساحة تحسين واحدة.</p></div><select value={type} onChange={(e)=>setType(e.target.value)} className="rounded-xl border border-border bg-white px-4 py-2 text-sm"><option value="all">كل الأنواع</option>{Object.entries(PAGE_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></header>{visible.length===0?<EmptyState icon={<IconOverview className="h-5 w-5"/>} title="لا توجد صفحات مطابقة" description="يعرض ظهور الصفحات التي زارها ووثقها فقط."/>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((page)=><Link key={page.id} href={`/stores/${storeId}/pages/${page.id}`}><Card padding="none" className="h-full overflow-hidden transition hover:-translate-y-1 hover:border-primary/30"><div className="aspect-[16/8] bg-neutral-tint">{page.image_url?<img src={page.image_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><IconOverview className="h-7 w-7 text-text-tertiary"/></div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><Badge variant="neutral">{PAGE_LABELS[page.page_type]??page.page_type}</Badge><h2 className="mt-2 line-clamp-2 font-bold text-text">{page.h1||page.title||"صفحة بلا عنوان مرصود"}</h2></div><span className="font-bold text-primary">{page.completion_score}%</span></div><p dir="ltr" className="mt-2 truncate text-left text-[11px] text-text-tertiary">{page.url}</p><div className="mt-4 flex items-center justify-between border-t border-border pt-3 text-sm font-semibold text-primary"><span>{page.issues_count} عناصر تحتاج مراجعة</span><IconArrowLeft className="h-4 w-4"/></div></div></Card></Link>)}</section>}</div>}
