"use client";
/* eslint-disable @next/next/no-img-element -- audited store images are external */

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ErrorState, LoadingState } from "@/components/ui/States";
import { IconCheckCircle, IconExternal, IconInfoCircle, IconSpark } from "@/components/ui/icons";
import { getIntents, getPages, getProducts, getStore, type IntentListItem, type PageWorkspaceItem, type ProductWorkspaceListItem, type StoreDetail } from "@/lib/api";
import { buildBulkCsv, buildLlmsTxt, buildOrganizationSchema, buildTechnicalAudit, contentIdeas, keywordStatus } from "@/lib/growth-workspace";

type Tab = "bulk" | "keywords" | "content" | "images" | "technical" | "artifacts";
const TABS: Array<{key:Tab;label:string}> = [
  {key:"bulk",label:"التحسين الجماعي"},{key:"keywords",label:"الكلمات والمتابعة"},{key:"content",label:"المحتوى والمقالات"},
  {key:"images",label:"الصور"},{key:"technical",label:"SEO وGEO التقني"},{key:"artifacts",label:"ملفات التنفيذ"},
];

export default function GrowthWorkspace() {
  const storeId=useParams<{id:string}>().id;
  const [tab,setTab]=useState<Tab>("bulk"); const [store,setStore]=useState<StoreDetail|null>(null);
  const [products,setProducts]=useState<ProductWorkspaceListItem[]|null>(null); const [pages,setPages]=useState<PageWorkspaceItem[]|null>(null); const [intents,setIntents]=useState<IntentListItem[]|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{Promise.allSettled([getStore(storeId),getProducts(storeId),getPages(storeId),getIntents(storeId)]).then(([s,p,g,i])=>{if(s.status==="rejected"){setError(String(s.reason));return}setStore(s.value);setProducts(p.status==="fulfilled"?p.value.products:[]);setPages(g.status==="fulfilled"?g.value.pages:[]);setIntents(i.status==="fulfilled"?i.value.intents:[]);});},[storeId]);
  if(error)return <ErrorState message={error}/>; if(!store||!products||!pages||!intents)return <LoadingState label="نجهّز مركز التحسين والتنفيذ..."/>;
  return <div className="flex flex-col gap-6 pb-16"><header><p className="text-xs font-semibold text-primary">مركز النمو والتنفيذ</p><h1 className="mt-1 text-3xl font-semibold text-text">حسّن المتجر كاملًا من مكان واحد</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-text-secondary">راجع الصفحات والكلمات والصور، ثم نزّل ملفات تنفيذ جاهزة. لا ننشر داخل المتجر قبل ربط المنصة واعتمادك للتغييرات.</p></header>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-border bg-white p-2">{TABS.map((item)=><button key={item.key} onClick={()=>setTab(item.key)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-medium transition ${tab===item.key?"bg-primary text-white shadow-sm":"text-text-secondary hover:bg-primary-tint hover:text-primary"}`}>{item.label}</button>)}</div>
    {tab==="bulk"&&<BulkPanel storeId={storeId} products={products} pages={pages}/>} {tab==="keywords"&&<KeywordsPanel intents={intents}/>} {tab==="content"&&<ContentPanel storeId={storeId} intents={intents}/>} {tab==="images"&&<ImagesPanel storeId={storeId} products={products}/>} {tab==="technical"&&<TechnicalPanel store={store} pages={pages}/>} {tab==="artifacts"&&<ArtifactsPanel store={store} pages={pages} products={products}/>} </div>;
}

function BulkPanel({storeId,products,pages}:{storeId:string;products:ProductWorkspaceListItem[];pages:PageWorkspaceItem[]}){
  const [selected,setSelected]=useState<Set<string>>(()=>new Set(products.filter((p)=>p.issues_count>0).map((p)=>p.id))); const toggle=(id:string)=>setSelected((old)=>{const next=new Set(old);if(next.has(id))next.delete(id);else next.add(id);return next;});
  const selectedProducts=products.filter((p)=>selected.has(p.id)); const missing=selectedProducts.reduce((n,p)=>n+p.issues_count,0);
  return <div className="grid gap-5 xl:grid-cols-[1.7fr_.8fr]"><Card padding="none" className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><h2 className="font-semibold text-text">قائمة المنتجات</h2><p className="text-xs text-text-tertiary">اختر ما تريد مراجعته أو تصديره كدفعة واحدة.</p></div><Button size="sm" variant="secondary" onClick={()=>setSelected(new Set(selected.size===products.length?[]:products.map((p)=>p.id)))}>{selected.size===products.length?"إلغاء الكل":"اختيار الكل"}</Button></div><div className="max-h-[620px] divide-y divide-border overflow-y-auto">{products.map((p)=><label key={p.id} className="grid cursor-pointer grid-cols-[auto_1fr_auto] items-center gap-3 p-4 hover:bg-surface-hover"><input type="checkbox" checked={selected.has(p.id)} onChange={()=>toggle(p.id)} className="h-4 w-4 accent-primary"/><div><p className="font-medium text-text">{p.name}</p><p className="mt-1 text-xs text-text-tertiary">{p.category_name||"بلا تصنيف مؤكد"} · {p.issues_count} عناصر تحتاج مراجعة</p></div><Link href={`/stores/${storeId}/products/${p.id}`} className="text-xs font-semibold text-primary">فتح الصفحة</Link></label>)}</div></Card><aside className="space-y-4"><Card padding="lg" className="border-primary/20 bg-primary-tint"><p className="text-sm text-primary">الدفعة الحالية</p><p className="mt-1 text-3xl font-bold text-text">{selected.size} منتجًا</p><p className="mt-2 text-sm text-text-secondary">{missing} عنصرًا يحتاج مراجعة، مبنية على صفحات تم رصدها فعلًا.</p><button onClick={()=>download("zuhoor-products.csv",buildBulkCsv(selectedProducts),"text/csv;charset=utf-8")} disabled={!selected.size} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">تنزيل ملف CSV للتنفيذ</button></Card><Card><h3 className="font-semibold text-text">تغطية المتجر</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="المنتجات" value={products.length}/><Metric label="الصفحات" value={pages.length}/><Metric label="جاهزة أساسيًا" value={products.filter((p)=>!p.issues_count).length}/><Metric label="تحتاج مراجعة" value={products.filter((p)=>p.issues_count>0).length}/></dl></Card><p className="rounded-xl border border-info/20 bg-info-tint p-4 text-xs leading-5 text-text-secondary">التوليد الجماعي والنشر المباشر سيصبحان خطوة اعتماد واحدة بعد ربط منصة المتجر. حاليًا تحصل على ملف قابل للمراجعة والتسليم دون تغيير المتجر.</p></aside></div>;
}

function KeywordsPanel({intents}:{intents:IntentListItem[]}){const measured=intents.filter((i)=>i.search_status==="measured");const top10=measured.filter((i)=>i.client_rank!==null&&i.client_rank<=10).length;return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Summary label="موضوعات البحث" value={intents.length} note="موضوعات ونوايا، وليست أعداد مشترين"/><Summary label="قياسات مكتملة" value={measured.length} note="نتائج رصد خارجية وقت الفحص"/><Summary label="ضمن أول 10" value={top10} note="من القياسات المكتملة فقط"/></div><Card padding="none" className="overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-semibold">متابعة الكلمات المرصودة</h2><p className="mt-1 text-xs text-text-tertiary">لا نعرض حجم بحث أو زيارات أو مبيعات ما لم تصل من مصدر مربوط.</p></div><div className="divide-y divide-border">{intents.map((intent)=>{const status=keywordStatus(intent);return <div key={intent.id} className="grid gap-3 p-4 md:grid-cols-[1.5fr_.8fr_.8fr_1fr] md:items-center"><div><p className="font-medium text-text">{intent.topic}</p><p className="text-xs text-text-tertiary">{intent.category||"غير مصنف"}</p></div><Badge variant={intent.commercial_stage==="purchase"?"warning":"neutral"}>{stageLabel(intent.commercial_stage)}</Badge><span className={`text-sm font-medium ${status.kind==="good"?"text-success":status.kind==="gap"?"text-danger":"text-text-tertiary"}`}>{status.label}</span><span className="text-xs text-text-tertiary">آخر رصد: {intent.search_observed_at?new Date(intent.search_observed_at).toLocaleDateString("ar-SA"):"غير متاح"}</span></div>})}</div></Card></div>}

function ContentPanel({storeId,intents}:{storeId:string;intents:IntentListItem[]}){const ideas=useMemo(()=>contentIdeas(intents),[intents]);const [open,setOpen]=useState<string|null>(null);return <div className="space-y-4"><Card className="border-primary/20 bg-primary-tint"><h2 className="font-semibold text-text">خطة محتوى مبنية على فجوات مرصودة</h2><p className="mt-2 text-sm text-text-secondary">الأفكار أدناه لا تعني وجود عدد محدد من الباحثين. كل فكرة مرتبطة بموضوع بحث وظهور مرصود، ويمكن تحويلها لاحقًا إلى مسودة كاملة عند الطلب.</p></Card>{ideas.length?ideas.map((idea)=><Card key={idea.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge variant="neutral">{stageLabel(idea.stage)}</Badge><h3 className="mt-2 text-lg font-semibold text-text">{idea.title}</h3><p className="mt-2 text-sm text-text-secondary">الدليل: {idea.evidence}</p></div><Button size="sm" variant="secondary" onClick={()=>setOpen(open===idea.id?null:idea.id)}>{open===idea.id?"إخفاء المخطط":"عرض مخطط المقال"}</Button></div>{open===idea.id&&<div className="mt-5 grid gap-3 border-t border-border pt-4 md:grid-cols-2"><div><h4 className="text-sm font-semibold">البنية المقترحة</h4><ol className="mt-2 list-decimal space-y-1 pe-5 text-sm text-text-secondary">{idea.outline.map((x)=><li key={x}>{x}</li>)}</ol></div><div className="rounded-xl bg-bg-subtle p-4"><p className="text-xs font-semibold text-primary">الخطوة التالية</p><p className="mt-2 text-sm text-text-secondary">افتح التوصيات لإنشاء المسودة الكاملة ومراجعتها قبل اعتمادها.</p><Link href={`/stores/${storeId}/recommendations`} className="mt-3 inline-block text-sm font-semibold text-primary">فتح التوصيات</Link></div></div>}</Card>):<Card><p className="text-sm text-text-secondary">لا توجد فجوات محتوى موثقة كافية حاليًا.</p></Card>}</div>}

function ImagesPanel({storeId,products}:{storeId:string;products:ProductWorkspaceListItem[]}){const withImages=products.filter((p)=>p.image_url);return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Summary label="منتجات بصور مرصودة" value={withImages.length} note={`من أصل ${products.length}`}/><Summary label="بلا صورة مرصودة" value={products.length-withImages.length} note="لا يعني أن المتجر بلا صورة"/><Summary label="جاهزة للفحص الفردي" value={withImages.length} note="الضغط والتحويل يتم عند الطلب"/></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{withImages.map((p)=><Link key={p.id} href={`/stores/${storeId}/products/${p.id}`}><Card padding="none" className="h-full overflow-hidden transition hover:-translate-y-1 hover:border-primary/30"><img src={p.image_url!} alt={p.name} className="aspect-square w-full bg-neutral-tint object-cover"/><div className="p-4"><h3 className="line-clamp-2 font-medium text-text">{p.name}</h3><p className="mt-2 text-xs text-primary">فتح فحص الصور والتحويل إلى WebP</p></div></Card></Link>)}</section><p className="rounded-xl border border-warning/20 bg-warning-tint p-4 text-xs text-text-secondary">التنزيل الجماعي والنشر التلقائي مؤجلان إلى طبقة الربط. لا يغيّر ظهور صور المتجر الحالية.</p></div>}

function TechnicalPanel({store,pages}:{store:StoreDetail;pages:PageWorkspaceItem[]}){const audit=buildTechnicalAudit(pages,store.url);return <div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><div className="space-y-3">{audit.map((item)=><Card key={item.key}><div className="flex items-start gap-3">{item.level==="ready"?<IconCheckCircle className="mt-0.5 h-5 w-5 text-success"/>:<IconInfoCircle className={`mt-0.5 h-5 w-5 ${item.level==="review"?"text-warning":"text-text-tertiary"}`}/>}<div><div className="flex gap-2"><h3 className="font-semibold text-text">{item.label}</h3><Badge variant={item.level==="ready"?"success":item.level==="review"?"warning":"neutral"}>{item.level==="ready"?"جيد":item.level==="review"?"يحتاج مراجعة":"غير مربوط"}</Badge></div><p className="mt-2 text-sm text-text-secondary">{item.detail}</p></div></div></Card>)}</div><aside className="space-y-4"><Card className="border-primary/20 bg-primary-tint"><IconSpark className="h-6 w-6 text-primary"/><h2 className="mt-3 font-semibold text-text">جاهزية البحث والذكاء الاصطناعي</h2><p className="mt-2 text-sm leading-6 text-text-secondary">نفحص وضوح الصفحات وبنيتها من البيانات المرصودة. لا نحوّل ذلك إلى درجة وهمية ولا نضمن الظهور في Google أو إجابات الذكاء الاصطناعي.</p></Card><Card><h3 className="font-semibold">ما يحتاج الربط لاحقًا</h3><ul className="mt-3 list-disc space-y-2 pe-5 text-sm text-text-secondary"><li>النقرات والانطباعات والتحويلات الفعلية.</li><li>حالة الفهرسة من Google Search Console.</li><li>إرسال Sitemap وطلبات الفهرسة.</li><li>النشر والتراجع داخل منصة المتجر.</li></ul></Card></aside></div>}

function ArtifactsPanel({store,pages,products}:{store:StoreDetail;pages:PageWorkspaceItem[];products:ProductWorkspaceListItem[]}){const profile=store.store_profile;const llms=buildLlmsTxt({name:profile?.name,url:store.url,description:profile?.description},pages);const schema=JSON.stringify(buildOrganizationSchema({name:profile?.name,url:store.url,description:profile?.description}),null,2);return <div className="grid gap-5 lg:grid-cols-2"><Artifact title="llms.txt" description="دليل مختصر للصفحات المهمة المرصودة. يحتاج اعتمادك قبل النشر." preview={llms} onDownload={()=>download("llms.txt",llms,"text/plain;charset=utf-8")}/><Artifact title="Organization Schema" description="بيانات المؤسسة المؤكدة فقط؛ نحذف الوصف عندما لا يكون متوفرًا." preview={schema} onDownload={()=>download("organization-schema.json",schema,"application/json")}/><Artifact title="قائمة المنتجات CSV" description="بيانات المنتجات وحالة الاكتمال لتسليمها أو مراجعتها جماعيًا." preview={`${products.length} صفًا جاهزًا للتصدير`} onDownload={()=>download("zuhoor-products.csv",buildBulkCsv(products),"text/csv;charset=utf-8")}/><Artifact title="تقرير التدقيق JSON" description="نتيجة التدقيق الحتمي على الصفحات المرصودة." preview="HTTPS، العناوين، H1، التكرار، وحالة الربط" onDownload={()=>download("zuhoor-audit.json",JSON.stringify(buildTechnicalAudit(pages,store.url),null,2),"application/json")}/></div>}

function Artifact({title,description,preview,onDownload}:{title:string;description:string;preview:string;onDownload:()=>void}){return <Card className="flex min-h-64 flex-col"><div className="flex items-start justify-between"><div><IconExternal className="h-5 w-5 text-primary"/><h2 className="mt-3 text-lg font-semibold">{title}</h2></div><Button size="sm" onClick={onDownload}>تنزيل</Button></div><p className="mt-2 text-sm text-text-secondary">{description}</p><pre dir="ltr" className="mt-4 max-h-44 flex-1 overflow-auto whitespace-pre-wrap rounded-xl bg-bg-subtle p-4 text-left text-xs text-text-secondary">{preview}</pre></Card>}
function Summary({label,value,note}:{label:string;value:number;note:string}){return <Card><p className="text-sm text-text-secondary">{label}</p><p className="mt-1 text-3xl font-bold text-text">{value}</p><p className="mt-2 text-xs text-text-tertiary">{note}</p></Card>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-bg-subtle p-3"><dt className="text-xs text-text-tertiary">{label}</dt><dd className="mt-1 text-xl font-bold text-text">{value}</dd></div>}
function stageLabel(stage:string|null){return stage==="purchase"?"قريب من القرار":stage==="consideration"?"مقارنة وتقييم":stage==="awareness"?"اكتشاف ومعرفة":"مرحلة غير مؤكدة"}
function download(name:string,content:string,type:string){const blob=new Blob(["\uFEFF",content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
