"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ErrorState, LoadingState } from "@/components/ui/States";
import { CompetitorListItem, CrossSurfaceIntentItem, IntentListItem, getCompetitors, getCrossSurfaceVisibility, getIntents } from "@/lib/api";
import { classificationLabel } from "@/lib/competitor-labels";

export default function CompetitorsPage(){
 const storeId=useParams<{id:string}>().id; const [competitors,setCompetitors]=useState<CompetitorListItem[]|null>(null); const [intents,setIntents]=useState<IntentListItem[]>([]); const [matrix,setMatrix]=useState<CrossSurfaceIntentItem[]>([]); const [showAll,setShowAll]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;Promise.all([getCompetitors(storeId),getIntents(storeId),getCrossSurfaceVisibility(storeId)]).then(([c,i,m])=>{if(active){setCompetitors(c.competitors);setIntents(i.intents);setMatrix(m.intents)}}).catch(e=>active&&setError(String(e)));return()=>{active=false}},[storeId]);
 if(error)return <ErrorState message={error}/>;if(!competitors)return <LoadingState/>;
 const direct=competitors.filter(c=>c.is_business_competitor).sort((a,b)=>b.serp_appearances-a.serp_appearances); const top=direct.slice(0,5); const leader=top[0]??null;
 const categoryScores=new Map<string,{seen:number,total:number}>(); intents.forEach(i=>{const k=i.category??"غير مصنف";const v=categoryScores.get(k)??{seen:0,total:0};v.total++;if(i.client_rank!==null&&i.client_rank<=10)v.seen++;categoryScores.set(k,v)}); const advantage=[...categoryScores].sort((a,b)=>(b[1].seen/b[1].total)-(a[1].seen/a[1].total))[0];
 const displayed=showAll?direct:top;
 return <div className="flex flex-col gap-8 pb-12"><header><h1 className="text-xl font-bold text-text">المنافسون</h1><p className="mt-1 text-sm text-text-secondary">من يتكرر أمام عملائك، وأين يقع متجرك بينهم؟</p></header>
 <section className="grid gap-3 md:grid-cols-3"><Metric label="منافسون مباشرون متكررون" value={direct.length?String(direct.length):"بيانات غير كافية"}/><Metric label="الأكثر ظهورًا أمامك" value={leader?.name||leader?.domain||"بيانات غير كافية"}/><Metric label="أفضلية متجرك" value={advantage&&advantage[1].seen?advantage[0]:"لم نرصد أفضلية بعد"}/></section>
 <section><h2 className="mb-1 font-semibold text-text">خريطة المنافسين</h2><p className="mb-3 text-xs text-text-tertiary">يمينًا: يظهر في عمليات بحث أكثر. أعلى: متوسط ترتيب أقوى. حجم الدائرة: مرات الظهور.</p><Card padding="md"><div className="relative h-[390px] overflow-hidden rounded-xl bg-bg-subtle"><div className="absolute inset-x-0 top-1/2 border-t border-dashed border-border-strong"/><div className="absolute inset-y-0 left-1/2 border-l border-dashed border-border-strong"/><Bubble label="متجرك" x={storeBreadth(intents)} y={storeStrength(intents)} size={44} store/>{top.map(c=><Bubble key={c.id} label={c.name||c.domain} x={competitorX(c,top)} y={c.avg_serp_rank===null?8:Math.max(8,100-(c.avg_serp_rank-1)*8)} size={Math.min(54,26+c.serp_appearances*2)}/>)}</div></Card></section>
 {matrix.length>0&&<section><h2 className="mb-1 font-semibold text-text">خريطة السيطرة على أهم موضوعات البحث</h2><p className="mb-3 text-xs text-text-tertiary">الخلايا تلخص الرصد المتاح، واضغط اسم المنافس للمقارنة التفصيلية.</p><Card padding="none" className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-bg-subtle"><tr><th className="p-3 text-right">موضوع البحث</th><th className="p-3">متجرك</th>{top.slice(0,4).map(c=><th key={c.id} className="p-3"><Link href={`/stores/${storeId}/competitors/${c.id}`}>{c.name||c.domain}</Link></th>)}</tr></thead><tbody className="divide-y divide-border">{matrix.slice(0,6).map(row=><tr key={row.stable_intent_id}><td className="p-3 font-medium text-text">{row.topic}</td><td className="p-3 text-center"><Strength values={Object.values(row.store_visibility)}/></td>{top.slice(0,4).map(c=><td key={c.id} className="p-3 text-center"><Strength values={Object.values(row.competitor_visibility[c.domain]??{})}/></td>)}</tr>)}</tbody></table></Card></section>}
 <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold text-text">المنافسون الحقيقيون</h2><p className="mt-1 text-xs text-text-tertiary">الأكثر تكرارًا في نفس عمليات البحث، لا كل نطاق ظهر مرة واحدة.</p></div>{direct.length>5&&<Button size="sm" variant="ghost" onClick={()=>setShowAll(!showAll)}>{showAll?"عرض الأهم فقط":"عرض البقية"}</Button>}</div><div className="space-y-3">{displayed.map(c=><Card key={c.id} padding="md"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-text">{c.name||c.domain}</h3><Badge variant="neutral">{classificationLabel(c.classification)}</Badge></div><Link href={`/stores/${storeId}/competitors/${c.id}`} className="text-sm font-medium text-primary">مقارنة</Link></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><Data label="ظهر في" value={`${c.serp_appearances} عمليات بحث`}/><Data label="متوسط الترتيب" value={c.avg_serp_rank===null?"بيانات غير كافية":c.avg_serp_rank.toFixed(1)}/><Data label="مشترك مع متجرك" value={`${c.shared_stable_intents_count} موضوعات`}/><Data label="إشارة التفوق" value={c.avg_serp_rank!==null&&c.avg_serp_rank<=5?"ترتيب متقدم":"تغطية متكررة"}/></div></Card>)}</div></section></div>
}
function Metric({label,value}:{label:string;value:string}){return <Card padding="md"><p className="text-xs text-text-tertiary">{label}</p><p className="mt-2 line-clamp-2 text-lg font-bold text-text">{value}</p></Card>}
function Data({label,value}:{label:string;value:string}){return <div><p className="text-xs text-text-tertiary">{label}</p><p className="mt-1 font-medium text-text">{value}</p></div>}
function Bubble({label,x,y,size,store=false}:{label:string;x:number;y:number;size:number;store?:boolean}){return <div className={`absolute flex -translate-x-1/2 translate-y-1/2 items-center justify-center rounded-full border-2 px-2 text-center text-[10px] font-semibold shadow-sm ${store?"z-10 border-primary bg-primary text-on-primary":"border-warning bg-warning-tint text-text"}`} style={{left:`${x}%`,bottom:`${y}%`,width:size,height:size}} title={label}>{label.slice(0,18)}</div>}
function Strength({values}:{values:number[]}){if(!values.length)return <span className="text-xs text-text-tertiary">لم نرصد</span>;const best=Math.max(...values);return <Badge variant={best>=.66?"success":best>=.33?"warning":"neutral"}>{best>=.66?"قوي":best>=.33?"متوسط":"ضعيف"}</Badge>}
function competitorX(c:CompetitorListItem,all:CompetitorListItem[]){const max=Math.max(1,...all.map(x=>x.serp_appearances));return 12+c.serp_appearances/max*76} function storeBreadth(i:IntentListItem[]){return 12+(i.filter(x=>x.client_rank!==null).length/Math.max(1,i.length))*76} function storeStrength(i:IntentListItem[]){const ranks=i.map(x=>x.client_rank).filter((x):x is number=>x!==null);if(!ranks.length)return 8;return Math.max(8,100-((ranks.reduce((a,b)=>a+b,0)/ranks.length)-1)*8)}
