"""measurement, alert tables and store scheduling fields

Revision ID: 00d592a7cbc5
Revises: a795b50f0b23
Create Date: 2026-08-11 17:22:21.083624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d592a7cbc5'
down_revision: Union[str, None] = 'a795b50f0b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('related_competitor_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('unread', 'read', 'dismissed', name='alertstatus'), nullable=False),
    sa.ForeignKeyConstraint(['related_competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['related_recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_store_id'), 'alerts', ['store_id'], unique=False)
    op.create_table('measurement_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('target_queries', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('target_prompts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('google_visibility', sa.Float(), nullable=True),
    sa.Column('ai_visibility', sa.Float(), nullable=True),
    sa.Column('page_metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('competitor_visibility', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_baselines_recommendation_id'), 'measurement_baselines', ['recommendation_id'], unique=True)
    op.create_table('measurement_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('google_visibility', sa.Float(), nullable=True),
    sa.Column('ai_visibility', sa.Float(), nullable=True),
    sa.Column('page_metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_snapshots_recommendation_id'), 'measurement_snapshots', ['recommendation_id'], unique=False)
    # server_default required: stores already has rows from every prior
    # baseline run in this environment, and this column is NOT NULL.
    op.add_column(
        'stores',
        sa.Column('monitoring_cadence', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='weekly'),
    )
    op.add_column('stores', sa.Column('next_scheduled_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'next_scheduled_run_at')
    op.drop_column('stores', 'monitoring_cadence')
    op.drop_index(op.f('ix_measurement_snapshots_recommendation_id'), table_name='measurement_snapshots')
    op.drop_table('measurement_snapshots')
    op.drop_index(op.f('ix_measurement_baselines_recommendation_id'), table_name='measurement_baselines')
    op.drop_table('measurement_baselines')
    op.drop_index(op.f('ix_alerts_store_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
