"""add opportunity consolidation

Revision ID: 0f46b194db44
Revises: 23d55bd4bd8d
Create Date: 2026-08-12 13:17:33.729088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f46b194db44'
down_revision: Union[str, None] = '23d55bd4bd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Part Q2 — same recurring lesson as every prior native-Postgres-ENUM
    # addition: ALTER TYPE ... ADD VALUE isn't picked up by autogenerate
    # and must run outside the alembic-managed transaction.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE opportunitystatus ADD VALUE IF NOT EXISTS 'merged'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('merged_into_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_opportunities_merged_into_id'), 'opportunities', ['merged_into_id'], unique=False)
    op.create_foreign_key(None, 'opportunities', 'opportunities', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_merged_into_id'), table_name='opportunities')
    op.drop_column('opportunities', 'merged_into_id')
    # ### end Alembic commands ###
    # Removing a value from a Postgres enum type isn't directly supported;
    # intentional no-op, same as every prior enum-add migration.
