"""research capabilities and dead-end task tracking

Revision ID: 165b4c5891df
Revises: c607f3ae7186
Create Date: 2026-08-12 01:46:52.558516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '165b4c5891df'
down_revision: Union[str, None] = 'c607f3ae7186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('origin_task_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_findings_origin_task_id'), 'findings', ['origin_task_id'], unique=False)
    op.create_foreign_key(None, 'findings', 'research_tasks', ['origin_task_id'], ['id'])
    # server_default required: research_tasks already has rows from prior
    # live runs (same recurring lesson as every NOT-NULL column added to a
    # populated table this session).
    op.add_column('research_tasks', sa.Column('new_findings_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('research_tasks', sa.Column('new_evidence_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('research_tasks', sa.Column('new_competitors_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('research_tasks', sa.Column('affected_opportunities_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('research_tasks', sa.Column('useful', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_research_tasks_useful'), 'research_tasks', ['useful'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_tasks_useful'), table_name='research_tasks')
    op.drop_column('research_tasks', 'useful')
    op.drop_column('research_tasks', 'affected_opportunities_count')
    op.drop_column('research_tasks', 'new_competitors_count')
    op.drop_column('research_tasks', 'new_evidence_count')
    op.drop_column('research_tasks', 'new_findings_count')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_index(op.f('ix_findings_origin_task_id'), table_name='findings')
    op.drop_column('findings', 'origin_task_id')
    # ### end Alembic commands ###
