"""add intent clustering

Revision ID: 23d55bd4bd8d
Revises: 2641391d338a
Create Date: 2026-08-12 13:08:35.438888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23d55bd4bd8d'
down_revision: Union[str, None] = '2641391d338a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_clusters_research_run_id'), 'intent_clusters', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_intent_clusters_store_id'), 'intent_clusters', ['store_id'], unique=False)
    op.add_column('intents', sa.Column('cluster_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_intents_cluster_id'), 'intents', ['cluster_id'], unique=False)
    op.create_foreign_key(None, 'intents', 'intent_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intents', type_='foreignkey')
    op.drop_index(op.f('ix_intents_cluster_id'), table_name='intents')
    op.drop_column('intents', 'cluster_id')
    op.drop_index(op.f('ix_intent_clusters_store_id'), table_name='intent_clusters')
    op.drop_index(op.f('ix_intent_clusters_research_run_id'), table_name='intent_clusters')
    op.drop_table('intent_clusters')
    # ### end Alembic commands ###
