"""add cancellation support to research_runs

Revision ID: 2641391d338a
Revises: 150920ea2de9
Create Date: 2026-08-12 12:48:25.321688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2641391d338a'
down_revision: Union[str, None] = '150920ea2de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Part H8 — same recurring lesson as every prior native-Postgres-ENUM
    # addition (Groups B/C/D/D2): ALTER TYPE ... ADD VALUE isn't picked up
    # by autogenerate and must run outside the alembic-managed transaction.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE runstatus ADD VALUE IF NOT EXISTS 'cancelled'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('cancel_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'cancel_requested_at')
    # ### end Alembic commands ###
    # Removing a value from a Postgres enum type isn't directly supported
    # (would require rebuilding the type); intentional no-op, same as every
    # prior enum-add migration in this project.
