"""beta readiness remediation: needs_validation status, recommendation confidence tier and claim structure

Revision ID: 2d3ef591275b
Revises: dbd59b1b5aef
Create Date: 2026-08-13 14:46:47.867075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d3ef591275b'
down_revision: Union[str, None] = 'dbd59b1b5aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Beta Readiness Remediation — same recurring lesson as every prior
    # native-Postgres-ENUM addition in this codebase: ALTER TYPE ... ADD
    # VALUE isn't picked up by autogenerate and must run outside the
    # alembic-managed transaction. Adds the "needs_validation" status to
    # BOTH opportunitystatus and recommendationstatus — see
    # app.opportunities.recommendation_engine's NO EVIDENCE → NO
    # RECOMMENDATION invariant.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE opportunitystatus ADD VALUE IF NOT EXISTS 'needs_validation'")
        op.execute("ALTER TYPE recommendationstatus ADD VALUE IF NOT EXISTS 'needs_validation'")

    # ### commands auto generated by Alembic - please adjust (server_default
    # added by hand so existing Round 1-3 recommendation rows backfill to
    # the same defaults the Python model uses, instead of failing NOT NULL) ###
    op.add_column(
        'recommendations',
        sa.Column('what_we_found', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    )
    op.add_column(
        'recommendations',
        sa.Column('why_this_improvement', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    )
    op.add_column(
        'recommendations',
        sa.Column('confidence_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='medium'),
    )
    op.add_column(
        'recommendations',
        sa.Column(
            'claim_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='observed_with_best_practice'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'claim_basis')
    op.drop_column('recommendations', 'confidence_tier')
    op.drop_column('recommendations', 'why_this_improvement')
    op.drop_column('recommendations', 'what_we_found')
    # ### end Alembic commands ###
    # Removing a value from a Postgres enum type isn't directly supported;
    # intentional no-op, same as every prior enum-add migration.
