"""research_tasks and findings tables

Revision ID: 30a5c1c40df6
Revises: b1d5a6cb88a1
Create Date: 2026-08-11 14:17:39.232515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a5c1c40df6'
down_revision: Union[str, None] = 'b1d5a6cb88a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('finding_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_intents', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_pages', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_competitors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'validated', 'rejected', name='findingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_research_run_id'), 'findings', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_findings_store_id'), 'findings', ['store_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Enum('seed_crawl', 'ai_classification', 'seed_intents', 'serp_batch', 'prompt_family_batch', 'ai_visibility_batch', 'competitor_discovery_batch', 'competitor_deep_dive', 'page_compare', 'query_expansion', 'validate_finding', name='tasktype'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hypothesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped_duplicate', name='taskstatus'), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('discovered_entities', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_tasks_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['research_tasks.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_fingerprint'), 'research_tasks', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_research_tasks_parent_task_id'), 'research_tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_research_run_id'), 'research_tasks', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_store_id'), 'research_tasks', ['store_id'], unique=False)
    op.add_column('ai_visibility_observations', sa.Column('origin_task_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ai_visibility_observations_origin_task_id'), 'ai_visibility_observations', ['origin_task_id'], unique=False)
    op.create_foreign_key(None, 'ai_visibility_observations', 'research_tasks', ['origin_task_id'], ['id'])
    op.add_column('serp_observations', sa.Column('origin_task_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_serp_observations_origin_task_id'), 'serp_observations', ['origin_task_id'], unique=False)
    op.create_foreign_key(None, 'serp_observations', 'research_tasks', ['origin_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serp_observations', type_='foreignkey')
    op.drop_index(op.f('ix_serp_observations_origin_task_id'), table_name='serp_observations')
    op.drop_column('serp_observations', 'origin_task_id')
    op.drop_constraint(None, 'ai_visibility_observations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_visibility_observations_origin_task_id'), table_name='ai_visibility_observations')
    op.drop_column('ai_visibility_observations', 'origin_task_id')
    op.drop_index(op.f('ix_research_tasks_store_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_research_run_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_parent_task_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_fingerprint'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_findings_store_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_research_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
