"""competitor classification taxonomy

Revision ID: 7e57a41fbe23
Revises: 74461952a294
Create Date: 2026-08-12 01:23:35.200324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e57a41fbe23'
down_revision: Union[str, None] = '74461952a294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_relationships', sa.Column('stable_intent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_competitor_relationships_stable_intent_id'), 'competitor_relationships', ['stable_intent_id'], unique=False)
    op.create_foreign_key(None, 'competitor_relationships', 'stable_intents', ['stable_intent_id'], ['id'])
    # server_default added by hand — competitors is already populated
    # (recurring lesson, same as every prior group's NOT NULL additions).
    # Historical rows default to "unknown"/0.0 — genuinely unclassified,
    # not a false claim of relevance — until a future run touches them
    # and app.competitors.classification reclassifies for real.
    op.add_column(
        'competitors',
        sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='unknown'),
    )
    op.add_column('competitors', sa.Column('relevance_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column(
        'competitors', sa.Column('classification_confidence', sa.Float(), nullable=False, server_default='0.0')
    )
    op.add_column('competitors', sa.Column('discovery_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('competitors', sa.Column('shared_stable_intents', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('competitors', sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.create_index(op.f('ix_competitors_classification'), 'competitors', ['classification'], unique=False)
    # ### end Alembic commands ###

    # Safe, additive data migration — backfills stable_intent_id on
    # existing competitor_relationships rows via the same intents.
    # stable_intent_id join used by every other F.5-0-style migration.
    op.get_bind().execute(
        sa.text(
            "UPDATE competitor_relationships SET stable_intent_id = intents.stable_intent_id "
            "FROM intents WHERE competitor_relationships.intent_id = intents.id"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_classification'), table_name='competitors')
    op.drop_column('competitors', 'evidence_ids')
    op.drop_column('competitors', 'shared_stable_intents')
    op.drop_column('competitors', 'discovery_reason')
    op.drop_column('competitors', 'classification_confidence')
    op.drop_column('competitors', 'relevance_score')
    op.drop_column('competitors', 'classification')
    op.drop_constraint(None, 'competitor_relationships', type_='foreignkey')
    op.drop_index(op.f('ix_competitor_relationships_stable_intent_id'), table_name='competitor_relationships')
    op.drop_column('competitor_relationships', 'stable_intent_id')
    # ### end Alembic commands ###
