"""ai visibility tables

Revision ID: 84605443d96c
Revises: 37819ad779df
Create Date: 2026-08-11 12:23:14.812045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84605443d96c'
down_revision: Union[str, None] = '37819ad779df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_families_intent_id'), 'prompt_families', ['intent_id'], unique=False)
    op.create_index(op.f('ix_prompt_families_research_run_id'), 'prompt_families', ['research_run_id'], unique=False)
    op.create_table('prompt_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prompt_family_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_family_id'], ['prompt_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_variants_prompt_family_id'), 'prompt_variants', ['prompt_family_id'], unique=False)
    op.create_table('ai_visibility_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_variant_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('ai_execution_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('search_enabled', sa.Boolean(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repetition_index', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('mention_position', sa.Integer(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('linked_domains', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('raw_artifact_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['ai_execution_id'], ['ai_executions.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['prompt_variant_id'], ['prompt_variants.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_visibility_observations_ai_execution_id'), 'ai_visibility_observations', ['ai_execution_id'], unique=False)
    op.create_index(op.f('ix_ai_visibility_observations_intent_id'), 'ai_visibility_observations', ['intent_id'], unique=False)
    op.create_index(op.f('ix_ai_visibility_observations_prompt_variant_id'), 'ai_visibility_observations', ['prompt_variant_id'], unique=False)
    op.create_index(op.f('ix_ai_visibility_observations_provider'), 'ai_visibility_observations', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_visibility_observations_research_run_id'), 'ai_visibility_observations', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_ai_visibility_observations_store_id'), 'ai_visibility_observations', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_visibility_observations_store_id'), table_name='ai_visibility_observations')
    op.drop_index(op.f('ix_ai_visibility_observations_research_run_id'), table_name='ai_visibility_observations')
    op.drop_index(op.f('ix_ai_visibility_observations_provider'), table_name='ai_visibility_observations')
    op.drop_index(op.f('ix_ai_visibility_observations_prompt_variant_id'), table_name='ai_visibility_observations')
    op.drop_index(op.f('ix_ai_visibility_observations_intent_id'), table_name='ai_visibility_observations')
    op.drop_index(op.f('ix_ai_visibility_observations_ai_execution_id'), table_name='ai_visibility_observations')
    op.drop_table('ai_visibility_observations')
    op.drop_index(op.f('ix_prompt_variants_prompt_family_id'), table_name='prompt_variants')
    op.drop_table('prompt_variants')
    op.drop_index(op.f('ix_prompt_families_research_run_id'), table_name='prompt_families')
    op.drop_index(op.f('ix_prompt_families_intent_id'), table_name='prompt_families')
    op.drop_table('prompt_families')
    # ### end Alembic commands ###
