"""opportunity and recommendation tables

Revision ID: a795b50f0b23
Revises: 30a5c1c40df6
Create Date: 2026-08-11 17:01:52.071634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a795b50f0b23'
down_revision: Union[str, None] = '30a5c1c40df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affected_intents', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_queries', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_pages', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('affected_products', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('finding_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('google_visibility_gap', sa.Float(), nullable=False),
    sa.Column('ai_visibility_gap', sa.Float(), nullable=False),
    sa.Column('competitor_gap', sa.Float(), nullable=False),
    sa.Column('estimated_impact', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effort_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commercial_relevance', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('scoring_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('open', 'actioned', 'dismissed', 'expired', name='opportunitystatus'), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_fingerprint'), 'opportunities', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_research_run_id'), 'opportunities', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_opportunities_store_id'), 'opportunities', ['store_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('first_seen_research_run_id', sa.Uuid(), nullable=False),
    sa.Column('last_seen_research_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('what_to_do', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why_it_matters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_page', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_intents', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('competitors_reference', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('expected_impact', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effort_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('implementation_steps', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('measurement_plan', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('implementation_package', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('new', 'planned', 'in_progress', 'implemented', 'dismissed', 'superseded', 'monitoring', 'successful', 'partial', 'no_detectable_impact', 'regressed', name='recommendationstatus'), nullable=False),
    sa.Column('implementation_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['last_seen_research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_fingerprint'), 'recommendations', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_recommendations_opportunity_id'), 'recommendations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_store_id'), 'recommendations', ['store_id'], unique=False)
    op.create_table('recommendation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_recommendation_id'), 'recommendation_history', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_research_run_id'), 'recommendation_history', ['research_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_history_research_run_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_recommendation_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_index(op.f('ix_recommendations_store_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_opportunity_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_fingerprint'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_opportunities_store_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_research_run_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_fingerprint'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
