"""ai visibility replay tracking

Revision ID: b09560ab9f77
Revises: 165b4c5891df
Create Date: 2026-08-12 11:20:08.854491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b09560ab9f77'
down_revision: Union[str, None] = '165b4c5891df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_visibility_observations', sa.Column('replayed_from_observation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ai_visibility_observations_replayed_from_observation_id'), 'ai_visibility_observations', ['replayed_from_observation_id'], unique=False)
    op.create_foreign_key(None, 'ai_visibility_observations', 'ai_visibility_observations', ['replayed_from_observation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_visibility_observations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_visibility_observations_replayed_from_observation_id'), table_name='ai_visibility_observations')
    op.drop_column('ai_visibility_observations', 'replayed_from_observation_id')
    # ### end Alembic commands ###
