"""ai visibility surface fields

Revision ID: b5ad349b120b
Revises: ebd428887178
Create Date: 2026-08-11 21:32:45.017408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ad349b120b'
down_revision: Union[str, None] = 'ebd428887178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand — ai_visibility_observations is already
    # populated, and a NOT NULL column addition needs one (recurring lesson
    # from every prior group's schema migrations in this project).
    op.add_column(
        'ai_visibility_observations',
        sa.Column('surface', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    )
    op.add_column(
        'ai_visibility_observations',
        sa.Column('grounding_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'ai_visibility_observations',
        sa.Column('citations_available', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('ai_visibility_observations', sa.Column('competitors_mentioned', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('ai_visibility_observations', sa.Column('products_mentioned', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('ai_visibility_observations', sa.Column('cited_domains', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.create_index(op.f('ix_ai_visibility_observations_surface'), 'ai_visibility_observations', ['surface'], unique=False)
    # ### end Alembic commands ###

    # Backfill historical rows' surface from their provider — before Part
    # F.5-2, provider/surface were an implicit 1:1 mapping
    # (openai->chatgpt, anthropic->claude, google->gemini); make that
    # explicit instead of leaving old rows with an empty surface.
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE ai_visibility_observations SET surface = CASE provider "
            "WHEN 'openai' THEN 'chatgpt' "
            "WHEN 'anthropic' THEN 'claude' "
            "WHEN 'google' THEN 'gemini' "
            "ELSE provider END"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_visibility_observations_surface'), table_name='ai_visibility_observations')
    op.drop_column('ai_visibility_observations', 'cited_domains')
    op.drop_column('ai_visibility_observations', 'products_mentioned')
    op.drop_column('ai_visibility_observations', 'competitors_mentioned')
    op.drop_column('ai_visibility_observations', 'citations_available')
    op.drop_column('ai_visibility_observations', 'grounding_enabled')
    op.drop_column('ai_visibility_observations', 'surface')
    # ### end Alembic commands ###
