"""finding multi-source validation

Revision ID: c607f3ae7186
Revises: 7e57a41fbe23
Create Date: 2026-08-12 01:32:07.797554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c607f3ae7186'
down_revision: Union[str, None] = '7e57a41fbe23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Same recurring lesson as every prior group: native Postgres ENUM
    # value additions aren't auto-detected and must run outside the
    # alembic-managed transaction.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE findingstatus ADD VALUE IF NOT EXISTS 'supported'")
        op.execute("ALTER TYPE findingstatus ADD VALUE IF NOT EXISTS 'insufficient_evidence'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('evidence_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('findings', sa.Column('confidence_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'confidence_explanation')
    op.drop_column('findings', 'evidence_breakdown')
    # ### end Alembic commands ###
