"""competitor and page intelligence tables

Revision ID: d37cadd4ccf1
Revises: c701a3b01898
Create Date: 2026-08-11 13:31:20.144911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd37cadd4ccf1'
down_revision: Union[str, None] = 'c701a3b01898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competitor_type', sa.Enum('search_competitor', 'ai_recommendation_competitor', name='competitortype'), nullable=False),
    sa.Column('first_seen_research_run_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_domain'), 'competitors', ['domain'], unique=False)
    op.create_index(op.f('ix_competitors_store_id'), 'competitors', ['store_id'], unique=False)
    op.create_table('competitor_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('serp', 'ai_visibility', name='relationshipsource'), nullable=False),
    sa.Column('rank_or_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_relationships_competitor_id'), 'competitor_relationships', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_relationships_intent_id'), 'competitor_relationships', ['intent_id'], unique=False)
    op.create_index(op.f('ix_competitor_relationships_research_run_id'), 'competitor_relationships', ['research_run_id'], unique=False)
    op.create_table('page_gap_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('competitor_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('recommendation_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_artifact_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_gap_analyses_competitor_id'), 'page_gap_analyses', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_page_gap_analyses_intent_id'), 'page_gap_analyses', ['intent_id'], unique=False)
    op.create_index(op.f('ix_page_gap_analyses_research_run_id'), 'page_gap_analyses', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_page_gap_analyses_store_id'), 'page_gap_analyses', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_gap_analyses_store_id'), table_name='page_gap_analyses')
    op.drop_index(op.f('ix_page_gap_analyses_research_run_id'), table_name='page_gap_analyses')
    op.drop_index(op.f('ix_page_gap_analyses_intent_id'), table_name='page_gap_analyses')
    op.drop_index(op.f('ix_page_gap_analyses_competitor_id'), table_name='page_gap_analyses')
    op.drop_table('page_gap_analyses')
    op.drop_index(op.f('ix_competitor_relationships_research_run_id'), table_name='competitor_relationships')
    op.drop_index(op.f('ix_competitor_relationships_intent_id'), table_name='competitor_relationships')
    op.drop_index(op.f('ix_competitor_relationships_competitor_id'), table_name='competitor_relationships')
    op.drop_table('competitor_relationships')
    op.drop_index(op.f('ix_competitors_store_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_domain'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
