"""store locale resolution fields

Revision ID: dbd59b1b5aef
Revises: 0f46b194db44
Create Date: 2026-08-12 23:56:28.347237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbd59b1b5aef'
down_revision: Union[str, None] = '0f46b194db44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stores', sa.Column('locale_confidence', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('locale_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stores', sa.Column('locale_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='unresolved'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'locale_status')
    op.drop_column('stores', 'locale_source')
    op.drop_column('stores', 'locale_confidence')
    op.drop_column('stores', 'market')
    # ### end Alembic commands ###
