"""stable intent identity

Revision ID: ebd428887178
Revises: 289a1f67492c
Create Date: 2026-08-11 20:58:25.837591

"""
import json
import re
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebd428887178'
down_revision: Union[str, None] = '289a1f67492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _normalize_topic(topic: str) -> str:
    # Mirrors app.models.stable_intent.normalize_topic exactly — duplicated
    # here on purpose (migrations must stay stable even if the app-side
    # function's implementation later changes).
    lowered = topic.strip().lower()
    stripped = re.sub(r"[^\w\s]", "", lowered, flags=re.UNICODE)
    return re.sub(r"\s+", " ", stripped).strip()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stable_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stable_intents_locale'), 'stable_intents', ['locale'], unique=False)
    op.create_index(op.f('ix_stable_intents_normalized_topic'), 'stable_intents', ['normalized_topic'], unique=False)
    op.create_index(op.f('ix_stable_intents_store_id'), 'stable_intents', ['store_id'], unique=False)
    op.add_column('ai_visibility_observations', sa.Column('stable_intent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ai_visibility_observations_stable_intent_id'), 'ai_visibility_observations', ['stable_intent_id'], unique=False)
    op.create_foreign_key(None, 'ai_visibility_observations', 'stable_intents', ['stable_intent_id'], ['id'])
    op.add_column('intents', sa.Column('stable_intent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_intents_stable_intent_id'), 'intents', ['stable_intent_id'], unique=False)
    op.create_foreign_key(None, 'intents', 'stable_intents', ['stable_intent_id'], ['id'])
    op.add_column('serp_observations', sa.Column('stable_intent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_serp_observations_stable_intent_id'), 'serp_observations', ['stable_intent_id'], unique=False)
    op.create_foreign_key(None, 'serp_observations', 'stable_intents', ['stable_intent_id'], ['id'])
    # ### end Alembic commands ###

    _backfill_stable_intents()


def _backfill_stable_intents() -> None:
    """Safe, additive data migration — no existing row is edited or
    deleted. Every historical Intent row is grouped by (store_id,
    normalized topic, country, language) into exactly one new
    StableIntent, then every table that references intent_id gets its new
    stable_intent_id populated from that grouping. Recommendation.target_intents
    (a JSONB list of intent-id strings, Group E) is remapped to the new
    stable-intent-id strings so existing recommendations keep working with
    the measurement loop instead of going permanently stale."""
    conn = op.get_bind()
    now = datetime.now(timezone.utc)

    intents_rows = conn.execute(
        sa.text("SELECT id, store_id, topic, country, language FROM intents ORDER BY created_at")
    ).fetchall()

    group_to_stable_id: dict[tuple, uuid.UUID] = {}
    intent_id_to_stable_id: dict[uuid.UUID, uuid.UUID] = {}

    insert_stable_intent = sa.text(
        """
        INSERT INTO stable_intents
            (id, created_at, store_id, canonical_topic, normalized_topic, country, language, locale, intent_type)
        VALUES
            (:id, :created_at, :store_id, :canonical_topic, :normalized_topic, :country, :language, :locale, NULL)
        """
    )

    for row in intents_rows:
        normalized = _normalize_topic(row.topic)
        key = (row.store_id, normalized, row.country, row.language)
        stable_id = group_to_stable_id.get(key)
        if stable_id is None:
            stable_id = uuid.uuid4()
            group_to_stable_id[key] = stable_id
            conn.execute(
                insert_stable_intent,
                {
                    "id": stable_id,
                    "created_at": now,
                    "store_id": row.store_id,
                    "canonical_topic": row.topic.strip(),
                    "normalized_topic": normalized,
                    "country": row.country,
                    "language": row.language,
                    "locale": f"{row.country}_{row.language}",
                },
            )
        intent_id_to_stable_id[row.id] = stable_id

    if intent_id_to_stable_id:
        update_intent = sa.text("UPDATE intents SET stable_intent_id = :stable_id WHERE id = :intent_id")
        conn.execute(
            update_intent,
            [{"stable_id": stable_id, "intent_id": intent_id} for intent_id, stable_id in intent_id_to_stable_id.items()],
        )

    conn.execute(
        sa.text(
            "UPDATE serp_observations SET stable_intent_id = intents.stable_intent_id "
            "FROM intents WHERE serp_observations.intent_id = intents.id"
        )
    )
    conn.execute(
        sa.text(
            "UPDATE ai_visibility_observations SET stable_intent_id = intents.stable_intent_id "
            "FROM intents WHERE ai_visibility_observations.intent_id = intents.id"
        )
    )

    rec_rows = conn.execute(sa.text("SELECT id, target_intents FROM recommendations")).fetchall()
    update_recommendation = sa.text(
        "UPDATE recommendations SET target_intents = CAST(:target_intents AS jsonb) WHERE id = :id"
    )
    for rec in rec_rows:
        old_list = rec.target_intents or []
        new_list = []
        changed = False
        for value in old_list:
            try:
                old_intent_id = uuid.UUID(value)
            except (ValueError, TypeError, AttributeError):
                new_list.append(value)
                continue
            stable_id = intent_id_to_stable_id.get(old_intent_id)
            if stable_id is not None:
                new_list.append(str(stable_id))
                changed = True
            else:
                new_list.append(value)
        if changed:
            conn.execute(update_recommendation, {"target_intents": json.dumps(new_list), "id": rec.id})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serp_observations', type_='foreignkey')
    op.drop_index(op.f('ix_serp_observations_stable_intent_id'), table_name='serp_observations')
    op.drop_column('serp_observations', 'stable_intent_id')
    op.drop_constraint(None, 'intents', type_='foreignkey')
    op.drop_index(op.f('ix_intents_stable_intent_id'), table_name='intents')
    op.drop_column('intents', 'stable_intent_id')
    op.drop_constraint(None, 'ai_visibility_observations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_visibility_observations_stable_intent_id'), table_name='ai_visibility_observations')
    op.drop_column('ai_visibility_observations', 'stable_intent_id')
    op.drop_index(op.f('ix_stable_intents_store_id'), table_name='stable_intents')
    op.drop_index(op.f('ix_stable_intents_normalized_topic'), table_name='stable_intents')
    op.drop_index(op.f('ix_stable_intents_locale'), table_name='stable_intents')
    op.drop_table('stable_intents')
    # ### end Alembic commands ###
