"""intent and serp tables

Revision ID: f81a4081de50
Revises: a251169020e4
Create Date: 2026-08-11 11:01:32.382661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81a4081de50'
down_revision: Union[str, None] = 'a251169020e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_text'), 'keywords', ['text'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('commercial_stage', sa.Enum('awareness', 'consideration', 'purchase', name='commercialstage'), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('estimated_demand', sa.Enum('low', 'medium', 'high', name='demandlevel'), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('deterministic_catalog', 'ai_expansion', name='intentsource'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_research_run_id'), 'intents', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_intents_source'), 'intents', ['source'], unique=False)
    op.create_index(op.f('ix_intents_store_id'), 'intents', ['store_id'], unique=False)
    op.create_table('intent_keywords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_keywords_intent_id'), 'intent_keywords', ['intent_id'], unique=False)
    op.create_index(op.f('ix_intent_keywords_keyword_id'), 'intent_keywords', ['keyword_id'], unique=False)
    op.create_table('serp_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=True),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', name='serpexecutionstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_artifact_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_executions_agent_run_id'), 'serp_executions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_serp_executions_provider'), 'serp_executions', ['provider'], unique=False)
    op.create_index(op.f('ix_serp_executions_research_run_id'), 'serp_executions', ['research_run_id'], unique=False)
    op.create_table('serp_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_rank', sa.Integer(), nullable=True),
    sa.Column('client_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_artifact_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_observations_intent_id'), 'serp_observations', ['intent_id'], unique=False)
    op.create_index(op.f('ix_serp_observations_keyword_id'), 'serp_observations', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_serp_observations_research_run_id'), 'serp_observations', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_serp_observations_store_id'), 'serp_observations', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serp_observations_store_id'), table_name='serp_observations')
    op.drop_index(op.f('ix_serp_observations_research_run_id'), table_name='serp_observations')
    op.drop_index(op.f('ix_serp_observations_keyword_id'), table_name='serp_observations')
    op.drop_index(op.f('ix_serp_observations_intent_id'), table_name='serp_observations')
    op.drop_table('serp_observations')
    op.drop_index(op.f('ix_serp_executions_research_run_id'), table_name='serp_executions')
    op.drop_index(op.f('ix_serp_executions_provider'), table_name='serp_executions')
    op.drop_index(op.f('ix_serp_executions_agent_run_id'), table_name='serp_executions')
    op.drop_table('serp_executions')
    op.drop_index(op.f('ix_intent_keywords_keyword_id'), table_name='intent_keywords')
    op.drop_index(op.f('ix_intent_keywords_intent_id'), table_name='intent_keywords')
    op.drop_table('intent_keywords')
    op.drop_index(op.f('ix_intents_store_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_source'), table_name='intents')
    op.drop_index(op.f('ix_intents_research_run_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_keywords_text'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
